### ISSUE TITLE
If you use an infernal shard on a witch it crashes the game.

### ISSUE THREAD

**Issue by Boodlyneck** [Lothrazar/VillagerTools#2]
Minecraft Version: 1.16.5

Forge Version: 36.1.3

Mod Version: 1.0.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

If you use an infernal shard on a witch it crashes the game.

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.entity.monster.WitchEntity cannot be cast to net.minecraft.entity.merchant.villager.WanderingTraderEntity
Exit Code: -1

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Thanks for your patience, got the fix out finally https://www.curseforge.com/minecraft/mc-mods/villager-tools/files/3405663
