### ISSUE TITLE
Smallish/important note

### ISSUE THREAD

**Issue by Kisonu** [Lothrazar/VillagerTools#3]
The curseforge page needs updated to specify this is a FORGE mod, as there are people using the FABRIC modloader coming across this mod, downloading it, and then finding out the hard way it's unusable.. good concept tho. 😁

**Comment by Lothrazar** [comment]
whats fabric? ive never heard of it.  

If fabric is a mod thats not compable with forge, sounds like a bug report you should send them

**Comment by Kisonu** [comment]
Fabric is the other HUGE modloader. Its Forge, but more focus on FASTER updates, SMOOTHER transitions between versions, MORE responsibility on the mod author for the functioning of the mods. Check it out here - https://fabricmc.net/
