### ISSUE TITLE
Cursed Pillager Amulet not working as intended

### ISSUE THREAD

**Issue by lartts** [Lothrazar/VillagerTools#5]
Minecraft Version: 
1.16.5

Forge Version: 
forge-36.1.0

Mod Version: 
villagertools-1.16.5-1.0.0.jar

Single Player or Server:
Single Player

Describe problem (what you were doing; what happened; what should have happened):
Decided to use a Cursed Pillager Amulet on a Pillager but instead of turning into a Town Guard, the Pillager disappeared. It can only be spawned using the /summon command and it acts like a Vindicator, aggressive against villagers and friendly towards illagers.

Log file link:

Video/images/gifs (direct upload or link): 
https://drive.google.com/file/d/1-pyuonUS79x54zm_fUwWTF3kZTWs6yF4/view?usp=sharing

**Comment by Lothrazar** [comment]
Thanks for your patience, got the fix out finally https://www.curseforge.com/minecraft/mc-mods/villager-tools/files/3405663
